### ISSUE TITLE
Crash With the Twilight Forest

### ISSUE THREAD

**Issue by AetherLegacyPro** [GTNewHorizons/Angelica#140]
### Mod Version

1.0.0-alpha12

### Java Version

Java 8

### Bug Report

[crash-2024-01-05_22.48.18-client.txt](https://github.com/GTNewHorizons/Angelica/files/13848258/crash-2024-01-05_22.48.18-client.txt)

[2024-01-05-7.log](https://github.com/GTNewHorizons/Angelica/files/13848259/2024-01-05-7.log)

### Mod List or GTNH Pack Version

![image(29)](https://github.com/GTNewHorizons/Angelica/assets/102751411/2fceee0c-835f-4795-93e6-af26155e1f19)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment]
I've only tried with the GTNH TF fork -- I'd recommend trying with that - it's mostly bugfixes.

**Comment by FlamingKetchup** [comment]
This crash happens because the GTNH fork of TF adds an opaque version of magic leaves for the Fast render setting
https://github.com/GTNewHorizons/twilightforest/commit/7587a8f8f310b2775924b2b6fbf8de54b976bbfb
and Angelica assumes that they are present
https://github.com/GTNewHorizons/Angelica/blob/1e71b1c4d8b6e2a1b1ee3b17223aff0604187ce3/src/mixin/java/com/gtnewhorizons/angelica/mixins/late/notfine/leaves/twilightforest/MixinBlockTFMagicLeaves.java

**Comment by FlamingKetchup** [comment]
A temporary fix for this is to disable NotFine features in the Angelica config

**Comment by twinkle-mouse** [comment]
This annoyingly also happens in Reika's DragonRealm modpack, which has a strict policy against updating mods due to Reika's custom modpack modifications.

@mitchej123 Can a config option be added to disable the mixin and/or have the mixin MixinBlockTFMagicLeaves not crash if the target isn't present? (Not sure if that's technically possible, haven't dabbled with mixins in a very long time.)

My testing of "neutering" the class with dirtyJOE makes Angelica function properly with the NotFine features on (alternatively NotFine features could be disabled to make it work too, but that's a lot of features)
