### ISSUE TITLE
Random white screen and game crash

### ISSUE THREAD

**Issue by paulzzh** [GTNewHorizons/Angelica#214]
### Your GTNH Discord Username

Paulzzh

### Mod Version

1.0.0-alpha15

### Java Version

Java 17

### Bug Report

https://mclo.gs/JK1qXjV
https://mclo.gs/6LKy8cl

Maybe a teleport or back to the game, then the game frozen on white screen.
Actually, the game has already crashed.
This happens 4-5 times a day.
https://github.com/GTNewHorizons/Jabba/blob/master/src/main/java/mcp/mobius/betterbarrels/client/render/BlockBarrelRenderer.java#L52
Maybe it's Jabba's problem?
<img width="960" alt="99e53b421ea5ae983e6fa3f8d8a90807" src="https://github.com/GTNewHorizons/Angelica/assets/28055560/90b3b020-b9b7-4c49-88cf-a809ec24d755">

### Mod List or GTNH Pack Version

GTNH 2.5.1
+lwjgl3ify 1.5.7
+Hodgepodge 2.4.8
+CCC +CCL
+GTNHLib 0.2.1

Angelica alpha13 alpha14 alpha15

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by MarshTheBacca** [comment]
I had a similar white screen crash when teleporting to a waypoint. I had the following mods:

GTNH 2.5.1
+Angelica 1.0.0-alpha36a
+lwjgl3ify 1.5.7
+Hodgepodge 2.4.40
+CodeChickenCore 1.2.1
+CodeChickenLib 1.1.10 (I didn't realise this, will update to 1.2.1)
+GTNHLib 0.2.11

The game crashed, then when trying to log back in, crashed a further two times immediately:
https://mclo.gs/Z43j0Z6
https://mclo.gs/hAMLrJC
https://mclo.gs/a7jjzv1

It mentions something about the inability to read the 'rotation' field of Jabba's barrel block because the barrel is null.

Upon restarting the game, I was able to log back in with no issues. Here is the crash scene:
![2024-04-16_07 06 22](https://github.com/GTNewHorizons/Angelica/assets/34864792/03983de4-598c-46b9-95e9-2d254ee53d12)

Inside the mountain behind the player in the screenshot, there are several barrels out of view.

As a side note, I absolutely love this mod, improved my performance from 30-40 FPS to 120+, incredible.

**Comment by mitchej123** [comment]
Looks like there might be some thread unsaftey in Jabba.  This is the primary concern.

The second trace is the tessellator getting into a bad state after the first crash and not being reset due to better crashes.  This is a secondary concern, would be nice if we cleaned it up after a crash.

**Comment by chochem** [comment]
same as https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15972?

**Comment by mitchej123** [comment]
> same as [GTNewHorizons/GT-New-Horizons-Modpack#15972](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15972)?

Looks that way
