### ISSUE TITLE
Occassional lighting Issue when near bedrock.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/Angelica#386]
### Your GTNH Discord Username

PlayfulPiano

### Mod Version

1.1.0-alpha34

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

https://github.com/GTNewHorizons/Angelica/assets/3158887/954fa56b-d843-4ad5-a3cc-70e84ee64469

Happens only at low y levels, occasionally everything turns black even with lighting nearby, but then after a while it just fixes itself sometimes.

### Mod List or GTNH Pack Version

GTNH 2.5.1
unimixins 0.1.16
gtnhlib 0.2.9
matmos 36.0.1
notenoughitems 2.5.17-GTNH
codechickencore 1.2.1
hodgepodge 2.4.9
justenoughcalculation 4.0
craftingtweaks 1.0.88
fullscreenwhileinactive 1.0.0
fullscreenwindowed 1.3.0b
dynamicsurroundings 1.0.6.4
itemphysiclite 1.1.5
fpsreducer 1.10.3

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by PlayfulPiano** [comment]
https://github.com/GTNewHorizons/Angelica/assets/3158887/2345e160-5c20-447d-9399-b377f6874bd1

Another instance example

**Comment by makamys** [comment]
This is a [vanilla "feature"](https://minecraft.wiki/w/Fog#Void_fog), I can reproduce this with and without Angelica.

Void fog appears when the skylight level gets below 7 or so, and gets thicker as the skylight level decreases. Note that this only happens in **survival** mode. Due to bugs in Minecraft's lighting engine, skylight can exist even in closed-off underground rooms. You can check the skylight level in the F3 overlay next to `sl:`.

https://github.com/GTNewHorizons/Angelica/assets/13667520/7557c891-a813-4618-beac-b8f11fb4e18a

We'll probably want to add an option to turn off void fog, considering it was removed in 1.8 and you'd be hard pressed to find anyone who likes it.
