### ISSUE TITLE
Ender Tanks weird rendering

### ISSUE THREAD

**Issue by zTotto** [GTNewHorizons/Angelica#390]
### Your GTNH Discord Username

totto.

### Mod Version

1.0.0-alpha34

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

![image](https://github.com/GTNewHorizons/Angelica/assets/49115537/c5088f03-de76-40b8-b436-b9a451c3d505)

The Ender tank is kind of invisible, sometimes also happens when in hotbar/inventory.

### Mod List or GTNH Pack Version

GTNH Nightly 390

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by oier-namespace-std** [comment]
This problem applies to nearly all TE storages, e.g. diamond chests on my client. ig this is a rendering problem of MC 1.7.10...

Maybe hard for gt:nh to fix?

**Comment by boubou19** [comment]
it's some open gl state leaking, annoying to track down, but if you want to help, try to isolate which one causes the leak.

**Comment by Cleptomania** [comment]
To expand on what @boubou19 said, the problem is sometimes caused by a completely unrelated TE.

There is potentially something leaking GL state, which then carries over to other mods which are expecting the state to be something else when they render. If you encounter this, a helpful thing to do is to sort of take an inventory of all the TEs being rendered on screen when it happens, and then in creative mode cycle through those and see which one causes it to happen, so we can narrow down the specific TE(or at the very least the specific mod) that's causing the issue.

We can patch the problems in mods that don't explicitly set the state they require, so a patch to EnderIO's rendering code is probably suitable here for the tanks, but it is better if we can get to the root of the problem where the GL state is leaking, because that generally should only be possible if there is a problem with Angelica's GLStateManager implementation.

**Comment by zTotto** [comment]
![image](https://github.com/GTNewHorizons/Angelica/assets/49115537/157711c6-5e70-4a67-a2df-81756499e823)
Ammonia does this, sometimes all ET in the inventory have a weird shade and also obscure vanilla blocks (i had cobblestone and dirt and the were darker than usual), this also happened when opening my Wireless Crafting Terminal

**Comment by eigenraven** [comment]
Did some debugging, the issue is present even without angelica, and is due to something very weird happening with the normals vertex attribute on the .obj model in CodeChickenLib. The code for filling this mixes some global object soup with local state and it's not really clear how the normals get corrupted, but they're different depending on if you hold it in your hand/display in hotbar/display in container.
