### ISSUE TITLE
EnderIO painted glowstone changing it's own texture randomly

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/Angelica#425]
### Your GTNH Discord Username

skproch

### Mod Version

1.0.0-alpha36a

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

Some painted glowstone (painted with burned quartz) randomly change it's texture to another block:

https://github.com/GTNewHorizons/Angelica/assets/29896317/72af837e-81b3-49a1-928d-9e1765590ed4

### Mod List or GTNH Pack Version

GTNH 2.6.0-beta3

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by SKProCH** [comment]
Also, this is affects EnderIO teleporter (his texture is glowstone in screenshot):

![image](https://github.com/GTNewHorizons/Angelica/assets/29896317/9d53d5ff-b488-4969-bfa0-e708a7e9c8c7)

**Comment by Cleptomania** [comment]
I'll have to dig more into the teleporter thing, but at least for the painted blocks.

The problem does not lie in EnderIO painted blocks, but rather what the block is painted with. In this case the extra utilities burnt quartz has a system where it uses connected textures on the static block class, which is probably not compatible with the multi-threading that happens to it as part of being painted by EnderIO in an ISBRH.

Not sure how/if to fix this given that it can't really be fixed in extra utilities the only possibility is with a mixin and that would have to be pretty heavy handed to replace this connected texture system with something else.

**Comment by Cleptomania** [comment]
Please see #439 which at least fixes the EnderIO painting for Extra Utilities(in addition to general thread safety for most of the Extra Utilities blocks)

**Comment by SKProCH** [comment]
Yep, seems like the painted glowstone is fixed, thanks, but teleporters still look like a glowstone sometimes. Should I open a new issue?
