### ISSUE TITLE
[1.7.10] SecurityCraft v1.8.13 incompatibility

### ISSUE THREAD

**Issue by Justus0405** [GTNewHorizons/Angelica#548]
### Your GTNH Discord Username

justus0405

### Mod Version

angelica-1.0.0-alpha52

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Bug Report

[1.7.10] SecurityCraft v1.8.13 crashes with angelica-1.0.0-alpha52 at the end of stage 2 when loading the game.

Logs captured with bettercrashes-1.4.0-GTNH :
https://mclo.gs/BX4CxKk

### Mod List or GTNH Pack Version

[1.7.10] SecurityCraft v1.8.13
+unimixins-all-1.7.10-0.1.17
angelica-1.0.0-alpha52
bettercrashes-1.4.0-GTNH
gtnhlib-0.3.1

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Shadowintelx** [comment]
Mod versions after Securitycraft version 1.7.3 crash. Only solution is to stick with version 1.7.3 until the problem is solved.

**Comment by brandyyn** [comment]
> Mod update versions after Securitycraft version 1.7.3 crash. Only solution is to stick with version 1.7.3 until the problem is solved.

https://github.com/quentin452/SecurityCraft

**Comment by konradmoesch** [comment]
Seems to be a duplicate of #541, i believe

**Comment by Cleptomania** [comment]
I'm going to say this is not an Angelica problem, the underlying problem is SecurityCraft using reflection to set a private field on Block, but the field has a setter function so that is completely unnecessary. I'm not sure why exactly Angelica causes that to fail, but that type of reflection is definitely unnecessary and nothing something we're gonna bother trying to support.

Problem needs fixed on SecurityCraft's side(be that via a fork of the mod or mixins to it elsewhere, it shouldn't be doing that regardless of Angelica being present).
