### ISSUE TITLE
Zoom hotkey

### ISSUE THREAD

**Issue by abel1502** [GTNewHorizons/Angelica#641]
### Feature Request

It would be nice to have an equivalent to optifine's zoom in hotkey. Not sure what else to add...

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by brandyyn** [comment]
use Zume.

**Comment by xdeadstokex** [comment]
@boubou19 while I agree that it's goal is the ultimate graphic mod, but putting everything together in a single mod is not ideal bcs some people might use that feature, some wont, so that will be a waste of space if a lot dont use that feature (not much, afew KB of space but still), also, if a mod already do what you want perfectly, why dont use it? Bcs the amount of time the dev spend on making a new already existed feature will has impact on the final product, also not to include bug issues,... So I think it is best to keep it modular, just put a link to Zume mod for those who want it.

**Comment by xdeadstokex** [comment]
@TheVitya2127 Like I say, other important part has not been finished (shader,...), so in the mean time, it is best to use Zume as an alternative, also add Zume to a mod pack increase ram but like what, a few mb, almost the same if it is putted in angelica (minus a few less kb for mod register)

**Comment by Cleptomania** [comment]
Like others have said, it’s probably very low on the priority list considering there is an open source, compatible, actively maintained and perfectly usable option available.

Much larger tasks that don’t have suitable alternatives before people are gonna be interested in dedicating time to this one if I had to guess

**Comment by brandyyn** [comment]
> Adding a new mod to a modpack increases RAM consumption

What’s funny is that the zoom module would literally just be Zume the mod embedded into Angelica … lmfao

**Comment by xdeadstokex** [comment]
good new, as of version beta 18, zoom has been added (dont know about it's quality yet), so this thread can be closed now.
