### ISSUE TITLE
Join, immediately disconnect, crash

### ISSUE THREAD

**Issue by StrongSilentLanguage** [GTNewHorizons/Angelica#778]
### Your GTNH Discord Username

natoc72

### Your Pack Version

2.7.0

### Your Server

private server

### Java Version

Java 8

### Type of Server

None

### Your Actions

Attempting to connect new account to new world. Previous version would connect, then immediately disconnect citing an index out of bounds error. Updated server and client to 2.7, successfully connect, immediately crash

### Crash Report

https://mclo.gs/QydRVO8

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Cleptomania** [comment]
I'm not sure what combination of things is causing the invalid metadata, that's gonna be insanely hard if even possible to get to the bottom of, it could be any number of mod combinations or interactions breaking something. However, I've added a PR to hodgepodge which at least causes it to not crash: https://github.com/GTNewHorizons/Hodgepodge/pull/448

I've added to hodgepodge because this seems to be more of a general problem with Witchery, and the code in witchery which was supposed to prevent a crash from it is just categorically wrong, so seemed more fitting to not to the fix to Angelica.
