### ISSUE TITLE
Various issues with Thaumcraft potion effect shaders

### ISSUE THREAD

**Issue by LordPINE** [GTNewHorizons/Angelica#86]
### Your GTNH Discord Username

lordpine

### Mod Version

1.0.0-alpha7

### Java Version

Java 8

### Bug Report

Some of Thaumcrafts potion effects only apply their shaders to the chat window (ID 34: unnatural hunger, ID 37: blurred vision, ID 38: Sun Scorned).
ID 36: Deadly Gaze causes the screen to do this. It seems like whatever it's applying doesn't get reset properly. Once it runs out the screen turns black and stays like that until the game is rebooted. Save and quite and reloading does not solve the problem.
![Deadly Gaze](https://github.com/GTNewHorizons/Angelica/assets/29479835/6c2c8f27-b681-49e8-b004-44dfbd76d6b0)
[fml-client-latest.log](https://github.com/GTNewHorizons/Angelica/files/13787036/fml-client-latest.log)

### Mod List or GTNH Pack Version

```
+unimixins-all-1.7.10-0.1.15
angelica-1.0.0-alpha2
Baubles-1.7.10-1.0.1.10
CodeChickenLib-1.2.0
CodeChickenCore-1.2.0
NotEnoughItems-2.4.13-GTNH
Thaumcraft-1.7.10-4.2.3.5
```

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by LordPINE** [comment]
This is without Iris being enabled. Just for completeness sake, all my config options are at their default values.

**Comment by Cleptomania** [comment]
FYI this works fine without HUDCaching enabled. These effects are all shader groups which hook into `RenderGameOverlayEvent` to render, and HUDCaching seems to be interfering with the shader updates(and to a worse extent with deadly gaze because that renders a separate vignette thing).

Need to investigate more but it is definitely caused by HUD Caching.

**Comment by Pistonight** [comment]
I investigated a bit and the issue seems to be that the vignette texture has no alpha channel. It is blended directly to the game frame in `renderVignette`. When blending into the cache frame, it causes the cached frame to lose alpha as well.

I am working on a fix which is to exclude vignette and portal from the cache. Thaumcraft uses portal events to draw vignette (presumbly because there's no vignette event).

@mitchej123 does the fix seem reasonable? I can also add a config option if needed to toggle between current behavior and fix :)

**Comment by mitchej123** [comment]
Interesting. Was renderVignette changed in later versions?  

I'm happy for any fixes, so if you think you have a handle on it please go for it.
